# Generated by Django 4.2.7 on 2023-11-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
