# Generated by Django 4.2.7 on 2023-11-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_webhook_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
