# Generated by Django 4.2.7 on 2023-11-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_discord_webhook_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receive_notifications",
            field=models.BooleanField(default=False),
        ),
    ]
