# Generated by Django 4.2.7 on 2023-11-16 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_receive_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="receive_notifications",
        ),
    ]
