  version: '3.8'

  # 참고: django, celery 는 docker hub 에서 deprecated 되어서 이제부터는 추가하지 않음. Python 으로 대체.
  # RabbitMQ 대신, redis 로 message broker 사용.

  services:
    web:
      build: .
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 3
      volumes:
        - .:/app
        - static_volume:/app/staticfiles
      ports:
        - "8000:8000"
      depends_on:
        - redis
    nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - static_volume:/app/staticfiles
      ports:
        - "80:80"
      depends_on:
        - web


    redis:
      image: redis:7.2.3-alpine3.18
      ports:
        - "6379:6379"

    celery:
      build: .
      command: celery -A core worker --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - web
        - redis

    celery-beat:
      build: .
      command: celery -A core beat --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - web
        - redis

  volumes:
    static_volume: