  version: '3.8'

  # 참고: django 는 docker hub 에서 deprecated 되어서 이제부터는 추가하지 않음. Python 으로 대체.
  # RabbitMQ 대신, redis 로 message broker 사용.
  
  services:
    web:
      build: .
      command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - redis

    redis:
      image: redis:7.2.3-alpine3.18
      ports:
        - "6379:6379"

    celery:
      build: .
      command: celery -A core worker --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - web
        - redis

    celery-beat:
      build: .
      command: celery -A core beat --loglevel=info
      volumes:
        - .:/app
      depends_on:
        - web
        - redis
