# Generated by Django 4.2.7 on 2023-11-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stalker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreferences",
            name="income_range",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="long_term_savings_goal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="primary_category_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_category_1",
                to="stalker.category",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="primary_category_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_category_2",
                to="stalker.category",
            ),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="saving_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="short_term_savings_goal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="userpreferences",
            name="spending_style",
            field=models.CharField(
                choices=[
                    ("conservative", "Conservative"),
                    ("moderate", "Moderate"),
                    ("aggressive", "Aggressive"),
                ],
                default="moderate",
                max_length=30,
            ),
        ),
    ]
